spring:
  datasource:
    url: jdbc:h2:mem:inter_transactions;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generateDdl: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        showSql: true
        useSqlComments: true
        formatSql: true
  h2:
    console.enabled: true
base:
  url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange


